# Déprécié, les fichiers de localisation se chargent maintenant de ça

TIPS = [
    "Astuce : Contrôler un seul zeppelin peut renverser le cours d'une bataille au bon moment.",
    "Citation : 'Celui qui maîtrise le vent, maîtrise la guerre.'",
    "Astuce : Les coffres volants sont une source précieuse d'or, ne les laissez pas filer.",
    "Citation : 'La stratégie est l'art de transformer le hasard en avantage.'",
    "Astuce : Les unités légères sont rapides mais fragiles, utilisez-les pour harceler l'ennemi.",
    "Citation : 'Une flotte unie est plus forte qu'un héros isolé.'",
    "Astuce : Méfiez-vous des tempêtes, elles frappent sans distinction entre alliés et ennemis.",
    "Citation : 'Le ciel appartient à ceux qui osent le conquérir.'",
    "Astuce : Placez vos Architectes proche des îles pour construire des tours et sécuriser vos positions.",
    "Citation : 'Défendre ses terres, c'est déjà préparer la victoire.'",
    "Astuce : Les Druids peuvent soigner vos troupes, protégez-les à tout prix.",
    "Citation : 'Dans la guerre, chaque souffle compte.'",
    "Astuce : Investir tôt dans un Léviathan peut impressionner, mais attention à ne pas négliger vos défenses.",
    "Citation : 'Le pouvoir sans prudence mène à la chute.'",
    "Astuce : Les bandits n'attaquent pas que vos ennemis… parfois, il vaut mieux esquiver que combattre.",
    "Citation : 'Le chaos des cieux ne pardonne pas l'arrogance.'",
    "Astuce : gardez toujours une armée chez vous. Votre ennemi a peut être envoyé quelqu'un.",
    "Buvez de l'eau, faites des pauses, et souvenez-vous que vous êtes géniaux !",
    "Un bon commandant ne prend pas de drogues, sauf du café éventuellement.",
    "1 + 1 = 1",
    "Ne jetez pas le cailliou dans la machine à laver, ça abîme les vêtements !",
    "Méfiez-vous de l'IA, sauf celle de Galad Islands ; elle est sympa !",
    "A ne pas reproduire chez soi !",
    "Ne refaisez pas ce jeu chez vous : ceci est réalisé par des professionnels !",
    "Astuce : Méfiez-vous de votre adversaire. Il est peut-être dans vos murs",
    "Nous ne sommes pas responsables des brisages d'amitiés.",
    "Si vous pensez que tout est fini, c'est que ce n'est que le début",
    "Astuce : Pour gagner, dites que votre adversaire a du pétrole. Les Etats-Unis viendront vous aider.",
    "Nos vaisseaux sont biodégradables. Pensez à l'environnement !",
    "Non, ce n'est pas la faute du jeu si vous perdez. Vous êtes juste nul.le.",
    "Non, ce n'est pas un singe qui joue contre vous.",
    "Test de filtre de beauté : ... Vous ne dépassez pas le seuil requis pour passer ce test.",
    "Promis, il n'y a pas de plagiat de Murder Drones dans ce jeu.", # Je me suis permis une ref à une SAE précédente
    "Attention, il est interdit à une IA d'affronter la notre.",
    "Tu savais que le jeu n'est pas disponible sur Steam ?",
    "T'as pas 100 balles pour le mettre sur Steam ?",
    "Les profesionnels ont des standards.",
    "Ce jeu a été fait avec amour (et surtout avec de la douleur)",
    "Enzo, tu peux débloquer le main ?",
    "All hail the git master",
    "La d'où on vient, on a un dompteur de goéland qui travaille dans l'armée.",
    "Comment ça, on vous dit plus de bétises que d'astuces ?"
]